---
- hosts: localhost
  become: true
  
  vars:
     package: vim
     doc_root: /var/www/example
     node_version: "8.1.4"
     node_prefix: "node-v{{node_version}}"
     node_tarball: "{{node_prefix}}.tar.gz"
     node_path: "/usr/local"
     python_version: "3.5.2"
     av_version: "0.99.2"
     certbot_version: "0.14.2"

  tasks:
    - include: tasks/clamav.yml

    - name: Obtaining the list of files in the web directory
      command: ls -1 /root/website
      register: command_result
      
    - include: tasks/checksum.yml
      with_items:
        - "{{ command_result.stdout_lines }}"

    - include: tasks/clamav.yml

    - include: tasks/node.yml   #setup node on remote server

    - include: tasks/apt.yml    #include repos through apt.
    
    - include: tasks/python.yml #setup python on remote server
    
    - include: tasks/certbot.yml
    
    
    - name: Create custom document root
      file: path={{ doc_root }} state=directory owner=www-data group=www-data

#     - name: Set up HTML file
#       copy: src=index.html dest={{ doc_root }}/index.html owner=www-data group=www-data mode=0644
# 
#     - name: Setup default Apache virtual host
#       template: src=vhost.tpl dest=/etc/apache2/sites-available/000-default.conf
    
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
