# - name: Check if certbot is already latest
#   command: certbot --version 
#   register: certbot_version_result
#   ignore_errors: True

- name: Install prerequisites
  apt: name=software-properties-common state=present
  # when: certbot_version_result.stdout.find('command not found') != -1

- name: Add certbot repo
  apt_repository: repo="ppa:certbot/certbot"
  # when: certbot_version_result.stdout.find('command not found') != -1

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    upgrade: dist

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    
# - name: Update and upgrade apt packages
#   become: true
#   apt:
#     upgrade: yes
#     update_cache: yes
#     cache_valid_time: 2

- name: Install certbot-nginx
  apt: name="python-certbot-nginx" state=present
  # when: certbot_version_result.stdout.find('command not found') != -1

- name: Install certbot-apache
  apt: name="python-certbot-apache" state=present
  # when: certbot_version_result.stdout.find('command not found') != -1

- copy:
    src: "{{ repo_path }}/certificate-install.sh"
    dest: "{{ website_root }}/certificate-install.sh"
    owner: root
    group: root
    mode: 0755


