- stat:
    path: "{{ website_root }}/{{ item }}"
  register: p
- debug:
    msg: "Path exists and is a directory"
  when: p.stat.isdir

- stat:
    path: "{{ website_root }}/checksum/{{item}}.md5"
  register: stat_result

- name: Create the file, if it doesnt exist already
  script: "{{ repo_path }}/checksum.sh" 
  when: not stat_result.stat.exists

#should run the below commands for all files

  

- set_fact:
    md5_value: "{{ lookup('file', '{{ website_root }}/checksum/{{ item }}.md5') }}"
  when: not p.stat.isdir
   

- stat:
    path: "{{ website_root }}/{{ item }}"
  register: existing_file
  when: not p.stat.isdir

- set_fact:
    file_integrity: "{{ existing_file.stat.md5 == md5_value }}"
  when: existing_file.stat.exists
  when: not p.stat.isdir
  
- name: Announce result for {{ item }}
  command: echo "Vulnerability detected!"
  when: not file_integrity

# - get_url:
#     url: http://example.com
#     dest: /my/dest/file
#     checksum: "md5:{{ md5_value }}"
#     force:  "{{ force_new_download | default ('false') }}"
  
# - set_fact:
#     md5_value: "{{ item }}"
#   with_urls:
#       - http://my_nexus_server.com:8081/nexus/service/local/artifact/maven/content?g=log4j&a=log4j&v=1.2.9&r=central&e=jar.md5

# - name: Run MD5 Checksum
#   command: bash checksum.sh
# 
# - name: Select files to copy
#   command: ls /root/devops/Devops/temp
#   register: files_to_copy
# 
# - name: Copy the checksum files
#   fetch: src=/remote/{{ item }} dest=/root/devops/prev
#   with_items: files_to_copy.stdout_lines