- name: Run MD5 Checksum
  command: bash checksum.sh

- name: Select files to copy
  command: ls /root/devops/Devops/temp
  register: files_to_copy

- name: Copy the checksum files
  fetch: src=/remote/{{ item }} dest=/root/devops/prev
  with_items: files_to_copy.stdout_lines