- name: clamAV | Checking installed version of clamAV
  shell: /usr/bin/clamscan "$(clamscan -V > )" = ClamAV {{av_version}}.*
  register: wanted_version_installed
  ignore_errors: True

- name: Install clamAV
  apt: name={{ item }} state=latest
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
  when: wanted_version_installed.rc == 1
  
- name: Update clamAV
  command: freshclam
  when: wanted_version_installed.rc == 1

- name: Run clamAV
  command: bash -c clamscan -r . |tail -n 9 >> av_result.txt
