- name: clamAV | Checking installed version of clamAV
  shell: clamscan -V 
  register: wanted_version_installed
  ignore_errors: True

- name: Install clamAV
  apt: name={{ item }} state=latest
  with_items:
    - clamav
    - clamav-daemon
    - clamav-freshclam
  when: wanted_version_installed.stdout.find('command not found') != -1
  
- name: Update clamAV
  command: freshclam
  #when: wanted_version_installed.stdout.find('command not found') != -1

- name: Run clamAV
  command: bash -c clamscan -r /root/website |tail -n 9 >> /root/website/av_result.txt
