# python_version is a given variable, eg. `3.5`
- name: Check if python is already latest
  command: python3 --version 
  register: python_version_result
  ignore_errors: True

- name: Install prerequisites
  apt: name=python-software-properties state=present
  when: python_version_result.stdout.find('command not found') != -1

- name: Add deadsnakes repo
  apt_repository: repo="ppa:fkrull/deadsnakes"
  when: python_version_result.stdout.find('command not found') != -1

- name: Install python
  apt: name="python3" state=present
  when: python_version_result.stdout.find('command not found') != -1
